### ISSUE TITLE
Email Field Editor sort is not working when field has replacement content.

### ISSUE THREAD

**Issue by snozza** [Financial-Times/email-meme-frontend#128]
<img width="1245" alt="screen shot 2016-07-17 at 16 26 48" src="https://cloud.githubusercontent.com/assets/6886844/16901428/4b1def60-4c3b-11e6-90f2-e021c3d8bec1.png">

**Comment by snozza** [comment]
the elements in the sort function don't seem to have an index property..

**Comment by venil7** [comment]
fixed now by #129
