### ISSUE TITLE
Can't scroll after selecting `rename property` in context menu

### ISSUE THREAD

**Issue by snozza** [Financial-Times/email-meme-frontend#261]
Lists data grid Context menu changes body style to `overflow:hidden`.
This reverts when you click away from context menu, but not when you select 'rename property' and subsequently close the modal. Means that scrolling is broken after this.

**Comment by GeekG1rl** [comment]
I noticed that when you add a new campaign to an email scrolling breaks as well

**Comment by venil7** [comment]
i cant replicate it anymore....

**Comment by syymza** [comment]
The problem is still there. It's not the grid scrollbar to break, but the window scrollpbar

**Comment by GeekG1rl** [comment]
Scrolling in the grid works. 
Scrolling in the window we don't seem to need in the grid works?

**Comment by GeekG1rl** [comment]
Done.
