### ISSUE TITLE
Date Range in Analytics has wrong dates

### ISSUE THREAD

**Issue by snozza** [Financial-Times/email-meme-frontend#350]
It uses the first and last dates of the emails, rather than the date range selected.

<img width="302" alt="screen shot 2016-10-25 at 22 19 13" src="https://cloud.githubusercontent.com/assets/6886844/19704819/36c0c294-9b01-11e6-8a54-5725257d4750.png">

**Comment by syymza** [comment]
This is being discussed :)
I believe we agreed to change "From" and "To" to actually indicate the real meaning of them
