### ISSUE TITLE
Expanding snippet selection window/dropdown

### ISSUE THREAD

**Issue by melanierogan** [Financial-Times/email-meme-frontend#359]
![unspecified](https://cloud.githubusercontent.com/assets/16557524/19765607/29cfbfb8-9c41-11e6-8746-5d841ad471b5.png)

Can we expand the 'add snippet' window to allow for the full name of the snippet? If it gets cut off it is really hard to tell which one you're selecting.

**Comment by GeekG1rl** [comment]
Done
