### ISSUE TITLE
Append additional email specific CSS in <style></style>

### ISSUE THREAD

**Issue by jonomilnes** [Financial-Times/email-meme-frontend#398]
Hi guys, this one is less of an issue, more a requirement that is probably unfeasible at this stage, but worth a mention if its at all possible.

Can functionality be added to allow the addition of CSS in the <style> tag at the Email creation stage?

Use case:
I use the CRM master template to create a new email, however I want to change a background image for mobile devices. This is a style that is specific to the email, and not any other that uses the master template, however cannot be inlined as it demands a media query.

It would be useful to have an extra field at email creation stage that will append any additional CSS to the <style> tag in the master template for this email only.

If you need me to explain further, just ask. Fully aware it's a big ask at this stage in the game!

**Comment by syymza** [comment]
As discussed, this is already possible placing a <content> area in your template <head>
