### ISSUE TITLE
Pagination and filter have issues when used together

### ISSUE THREAD

**Issue by syymza** [Financial-Times/email-meme-frontend#409]
When you are on a page > 1 and you start filtering, the pagination is kept throughout the search. This means that you'll see an empty list of results (even if in reality there are results on page 1).
![screen shot 2016-11-18 at 11 31 08](https://cloud.githubusercontent.com/assets/419147/20428756/a4d031a0-ad82-11e6-8f2b-fe48c524af47.png)

**Comment by snozza** [comment]
fixed
