### ISSUE TITLE
B2B/B2C units

### ISSUE THREAD

**Issue by melanierogan** [Financial-Times/email-meme-frontend#418]
Non mvp. But could we have the ability to scroll between b2b and b2c emails, e.g. click 'b2c only' would show only the b2c emails. Just makes it easier for users from each team not to get confused when editing.

**Comment by syymza** [comment]
This il somehow linked to #346. The proposed solution of allowing multiple tags/labes would allow you to filter by a specific tag (e.g. B2B)

**Comment by venil7** [comment]
ok, i'm closing it as duplicate then
