### ISSUE TITLE
Image library full path

### ISSUE THREAD

**Issue by melanierogan** [Financial-Times/email-meme-frontend#427]
I wanted to be sure it's ok to have two https:// in the full path of the images that come from MeMe. I'm worried this may cause issues in certain email clients. 
e.g.
https://www.ft.com/__origami/service/image/v2/images/raw/https://email-platform-ftcom-meme.s3.amazonaws.com/583f0442c9e0a80018d1bf7c?source=ft-email-manual&width=800&fit=scale-down

**Comment by venil7** [comment]
yes, the second `https://` is the query part of the URL, so its perfectly fine and valid URL,

do you have any specific email clients in mind?
