### ISSUE TITLE
Image library - search

### ISSUE THREAD

**Issue by melanierogan** [Financial-Times/email-meme-frontend#451]
When searching for a prefix, e.g. 'FT' it picks up everything with 'ft'...including, for example, pffffffffft.jpg.
Could we narrow down the search feature so it picks up just the prefix?

**Comment by GeekG1rl** [comment]
That might not be a wise thing to implement, I'll come chat to you in a min 🐙

**Comment by melanierogan** [comment]
Agreed, as discussed the search feature is fine as is. Closing this.
