### ISSUE TITLE
MeMe slow to load on larger emails

### ISSUE THREAD

**Issue by melanierogan** [Financial-Times/email-meme-frontend#452]
On emails with a large number of content blocks, the email can take a long time to respond/load. I'm wondering if this is to do with the number of content blocks, length and size of email? If so, could we have a look and if not, what might cause such slow loading/response?
e.g. the crm base template (has 30 odd blocks).

**Comment by snozza** [comment]
Will investigate what the bottle neck is (likely due to something affected by the content blocks as you suggested)

**Comment by GeekG1rl** [comment]
Done, list view included as well
