### ISSUE TITLE
Scheduling future sends 

### ISSUE THREAD

**Issue by Zak-Rautenbach** [Financial-Times/email-meme-frontend#457]
I never like to 'send immediately' always preferring to schedule in the future (even if it is just 10 minutes), I just tried to schedule a future send using the clock/calendar, even though I had it down as 6:00pm  09 Jan 2017 I got an error message saying that it wasn't a valid send time.

**Comment by snozza** [comment]
@Zak-Rautenbach It's the 10th of Jan Today...09 Jan will return you an invalid date

**Comment by Zak-Rautenbach** [comment]
@snozza It was the 9th (in the UK) when I tried to schedule.

I will try with a test send in case it was me being stupid.
