### ISSUE TITLE
Error messages / Notifications time

### ISSUE THREAD

**Issue by Zak-Rautenbach** [Financial-Times/email-meme-frontend#459]
Please could error messages display for a little longer (or have to be be manually closed), this is to make sure that the error is acknowledged and noted.

**Comment by snozza** [comment]
Will do so

**Comment by GeekG1rl** [comment]
This may help https://github.com/indexiatech/re-notif/pull/33/files

**Comment by GeekG1rl** [comment]
Kind of done, not click-to-close yet but extended to ten seconds.

**Comment by Zak-Rautenbach** [comment]
Thanks
