### ISSUE TITLE
Copying figures and email names from analytics area

### ISSUE THREAD

**Issue by Zak-Rautenbach** [Financial-Times/email-meme-frontend#464]
It would be most helpful if it was possible to highlight and copy the individual stats and email name from the main analytics page.

**Comment by GeekG1rl** [comment]
@Zak-Rautenbach how much do you need this? Looks like it's quite a bit of a pain with the way we're currently rendering stuff.. Can you use the CSV download?

**Comment by Zak-Rautenbach** [comment]
@GeekG1rl following our chat, let's try to fix this although we are happy to keep using the work around in the short term.

**Comment by GeekG1rl** [comment]
Done
