### ISSUE TITLE
Data upload notification/more prominent

### ISSUE THREAD

**Issue by Karishma-Kothari** [Financial-Times/email-meme-frontend#466]
When uploading data files to the 'Lists' section of meme, it is extremely difficult to see if a file upload is in progress as there is no loading icon. Is it possible to have this feature so that we know an upload is in progress and it prevents us from re-uploading? It would also be great to receive an email confirmation similar to exact target with the details of the upload once complete.

**Comment by snozza** [comment]
This is done. When you click save a loading screen comes up
