### ISSUE TITLE
Saving email in editor after making changes

### ISSUE THREAD

**Issue by Karishma-Kothari** [Financial-Times/email-meme-frontend#472]
Hi There

I have noticed that when I make changes to several snippets in the email editor and press save, MeMe only saves part of the edits. However I noticed that when I press send after each snippet change MeMe saves all changes perfectly fine. We should really be able to edit and save the whole email regardless of whether we are making changes to several parts of the email or just one snippet. Can this be updated please?

**Comment by snozza** [comment]
@Karishma-Kothari this should be fixed? Can you confirm?

**Comment by Karishma-Kothari** [comment]
@snozza I haven't noticed any further issues with this so it does seem to be fixed. You can close this for the time being.

**Comment by snozza** [comment]
cool beans!
