### ISSUE TITLE
Analytics view of clicks per link

### ISSUE THREAD

**Issue by Karishma-Kothari** [Financial-Times/email-meme-frontend#473]
Since we don't have a heatmap, it would be great to see in the link performance for each email in the analytics. We often have requests from editorial to report back on how many clicks certain articles produce and we often need to see which part of an email is performing better than others.

**Comment by GeekG1rl** [comment]
@Karishma-Kothari you can already do that :) Go into 'Analytics' tab, click on an email, then 'Unique Click' stat box, it's the 'URL Links' tab that should give you all the info. Let me know if you need anything else.
