### ISSUE TITLE
Saving a plain text version

### ISSUE THREAD

**Issue by Zak-Rautenbach** [Financial-Times/email-meme-frontend#485]
Moving the conversation on to here- we like to have the option to automatically save a plain text version of the html. There still needs to be an option for the plain text version to be saved separately. 

Whether this be a dialogue box with a 'save my choice' option or a tick box in the '+' section, we can work together to figure out what is most user friendly.

**Comment by snozza** [comment]
There's a version of this in place now. Let me know what you think.

**Comment by Zak-Rautenbach** [comment]
Thank you, will test it out
